<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SMILE.Engine\SMILE.Engine.csproj" />
    <ProjectReference Include="..\SMILE.Toolchains\SMILE.Toolchains.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Highlighting\SMILE.xshd"
                      LogicalName="SMILE.Desktop.Highlighting.SMILE.xshd" />
    <EmbeddedResource Include="Highlighting\MasmX64.xshd"
                      LogicalName="SMILE.Desktop.Highlighting.MasmX64.xshd" />
    <EmbeddedResource Include="Highlighting\Cobol.xshd"
                      LogicalName="SMILE.Desktop.Highlighting.Cobol.xshd" />
    <EmbeddedResource Include="Highlighting\Swift.xshd"
                      LogicalName="SMILE.Desktop.Highlighting.Swift.xshd" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
    <Version>0.4.3.1</Version>
    <AssemblyVersion>0.4.3.1</AssemblyVersion>
    <FileVersion>0.4.3.1</FileVersion>
    <InformationalVersion>0.4.3.1 Final Target Identifier and Header Hygiene</InformationalVersion>
  </PropertyGroup>

</Project>
