<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SMILE.Engine\SMILE.Engine.csproj" />
    <ProjectReference Include="..\..\src\SMILE.Desktop\SMILE.Desktop.csproj" />
    <ProjectReference Include="..\..\src\SMILE.Toolchains\SMILE.Toolchains.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\examples\TypedExpressionCore.smile"
          Link="examples\TypedExpressionCore.smile"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
